// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoP1_final.Data;

#nullable disable

namespace ProyectoP1_final.Migrations
{
    [DbContext(typeof(ProyectoP1_finalContext))]
    partial class ProyectoP1_finalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoP1_final.Models.Habitacion", b =>
                {
                    b.Property<int>("HabitacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitacionID"), 1L, 1);

                    b.Property<int?>("NumeroHabitacion")
                        .HasColumnType("int");

                    b.HasKey("HabitacionID");

                    b.ToTable("Habitacion");
                });

            modelBuilder.Entity("ProyectoP1_final.Models.Huesped", b =>
                {
                    b.Property<int>("HuespedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HuespedID"), 1L, 1);

                    b.Property<string>("NombreHuesped")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HuespedID");

                    b.ToTable("Huesped");
                });

            modelBuilder.Entity("ProyectoP1_final.Models.Reserva", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ID"), 1L, 1);

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitacionID")
                        .HasColumnType("int");

                    b.Property<int>("HuespedID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HabitacionID");

                    b.HasIndex("HuespedID");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("ProyectoP1_final.Models.Reserva", b =>
                {
                    b.HasOne("ProyectoP1_final.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoP1_final.Models.Huesped", "Huesped")
                        .WithMany("Reservas")
                        .HasForeignKey("HuespedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Huesped");
                });

            modelBuilder.Entity("ProyectoP1_final.Models.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProyectoP1_final.Models.Huesped", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
